name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        standard: [c11, c17]
    steps:
    - uses: actions/checkout@v4
    - name: Make bash script executable
      run: chmod +x scripts/workflow.build.sh build ${{ matrix.standard }}
    
    - name: Test pmargp build standard 📦
      run: ./scripts/workflow.build.sh test ${{ matrix.standard }}

